### ISSUE TITLE
Refactor into "real" custom component

### ISSUE THREAD

**Issue by torrottum** [torrottum/ikea-ansluta-esphome#7]
I think it's better to create a real/proper custom component for esphome.

I haven't figured out all the details yet, but currently I'm thinking the configuration should be something like this (to support the features currently in the develop branch as of commit [bf87676](https://github.com/torrottum/ikea-ansluta-esphome/tree/bf87676873aee6d68982079c10e3bfe159983d04)):

```yaml
# Other esphome stuff

spi:
  clk_pin: GPIO14
  miso_pin: GPIO12
  mosi_pin: GPIO13

ikea_ansluta:
  cs_pin: GPIO15

# Two remotes
light:
  - platform: ikea_ansluta
    name: "IKEA Ansluta 1"
    remote_address: '0x35c0'
  - platform: ikea_ansluta
    name: "IKEA Ansluta 2"
    remote_address: '0x35c1'
```

I've looked a bit into how the Tuya components in 1.15.0 works and I think it should be doable.

What I'm not sure about yet is how to solve #2, but I think doing this way will add more flexibility for solving that problem.

## Todo
- [ ] Refactor radio
  - [x] Config schema
  - [x] Needs to be SPIDevice
  - [x] Use uint8_t instead of char
  - [x] Use uint16_t instead of short
  - [x] Need to switch from Arduino methods
  - [x] A way to register callbacks
  - [ ] Debounce remote presses
- [x] Refactor ansluta_light
  - [x] Config schema
  - [x] Register callback
  - [x] Handle callback
- [x] Clean up code
- [ ] Write upgrade guide
- [x] Move yaml to example folder

**Comment by torrottum** [comment]
Seems to crash after running for a while. Not sure if this is something that has always happened or something new.
